/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_mksh_jzorba_JZorba */

#ifndef _Included_io_github_mksh_jzorba_JZorba
#define _Included_io_github_mksh_jzorba_JZorba
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    initZorba
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorba_initZorba
  (JNIEnv *, jclass);

/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    shutdownZorba
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorba_shutdownZorba
  (JNIEnv *, jclass);

/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    addURIPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorba_addURIPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    getURIPath
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_io_github_mksh_jzorba_JZorba_getURIPath
  (JNIEnv *, jobject);

/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    loadDocument
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorba_loadDocument
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    getDocument
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_mksh_jzorba_JZorba_getDocument
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_mksh_jzorba_JZorba
 * Method:    removeDocument
 * Signature: (Ljava/lang/String;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_io_github_mksh_jzorba_JZorba_removeDocument
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class io_github_mksh_jzorba_JZorbaQuery */

#ifndef _Included_io_github_mksh_jzorba_JZorbaQuery
#define _Included_io_github_mksh_jzorba_JZorbaQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_mksh_jzorba_JZorbaQuery
 * Method:    doLoadContextDocument
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorbaQuery_doLoadContextDocument
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_mksh_jzorba_JZorbaQuery
 * Method:    doCompile
 * Signature: (Lio/github/mksh/jzorba/JZorba;)V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorbaQuery_doCompile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_mksh_jzorba_JZorbaQuery
 * Method:    execute
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_mksh_jzorba_JZorbaQuery_execute
  (JNIEnv *, jobject);

/*
 * Class:     io_github_mksh_jzorba_JZorbaQuery
 * Method:    setContextDocument
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_mksh_jzorba_JZorbaQuery_setContextDocument
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
